apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
images:
- name: 192.168.118.100:30002/library/demo-api
  newTag: v7
patches:
- path: patch-resources.yaml
- path: patch-ingress.yaml
- path: patch-configmap.yaml

