apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pan20020422/gitops-config.git
    targetRevision: main
    path: apps/demo-api/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:            # ⚠️ 忽略 HPA 管理的副本数字段，避免与 selfHeal 打架
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  # 保护手动创建的harbor镜像拉取secret，不要被prune删除
  - group: ""
    kind: Secret
    name: harbor-cred
    jsonPointers:
    - /data

